config/routes.rb
StudyClosureTable::Application.routes.draw do
  resources :comments

  resources :posts

end

app/models/comment.rb
# -*- coding: utf-8 -*-
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :parent, foreign_key: 'parent_id', class_name: 'Comment'
  has_many :children, foreign_key: 'parent_id', class_name: 'Comment'

  has_many :ancestor_tree_paths, class_name: 'CommentTreePath', foreign_key: 'descendant_id'
  has_many :ancestors, through: :ancestor_tree_paths, source: 'ancestor'

  has_many :descendant_tree_paths, class_name: 'CommentTreePath', foreign_key: 'ancestor_id'
  has_many :descendants, through: :descendant_tree_paths, source: 'descendant'

  before_validation :disallow_move_inside, on: :update, if: ->(x){ x.parent_id_changed? }

  validates :post_id, presence: true
  validates :content, presence: true
  validate :must_same_post_if_belong_to_parent

  after_create :create_paths
  after_update :move_tree, if: ->(x){ x.parent_id_changed? }

  def distance_to(descendant)
    connection.select_value <<SQL
SELECT COUNT(*)
  FROM comment_tree_paths
 WHERE
   descendant_id = #{descendant.id}
   AND ancestor_id IN (
       SELECT descendant_id
         FROM comment_tree_paths
        WHERE ancestor_id = #{id}
          AND descendant_id != #{id}
   )
SQL
  end

  protected

  # 追加したコメントへのパスを作る
  #
  # * 自分と先祖へのパスを作る
  #
  def create_paths
    connection.execute <<SQL
INSERT INTO comment_tree_paths (ancestor_id, descendant_id)
  SELECT t.ancestor_id, #{id}
    FROM comment_tree_paths AS t
   WHERE t.descendant_id = #{parent.try(:id) || 'NULL'}
UNION ALL
  SELECT #{id}, #{id}
SQL
  end

  # サブツリー内への移動は許可しない
  #
  def disallow_move_inside
    if parent_id.in? descendants.pluck(:comment_id)
      errors.add(:parent_id, 'can not move inside subtree')
    end
  end

  # 親子関係にある場合、同じ Post に属している必要がある
  #
  def must_same_post_if_belong_to_parent
    return unless parent.try(:post) && post

    if parent.post.id != post.id
      errors.add(:post_id, :mismatch)
    end
  end

  # 指定した親の子供に移動させる
  #
  # * サブツリー内のパスは維持したまま、サブツリー内のノードへの余計な参照を切る
  # * CROSS JOIN を用いたデカルト積で、移動先ノードを子孫とするノードからの参照を作る
  #
  def move_tree
    connection.execute <<SQL
DELETE FROM comment_tree_paths
 WHERE descendant_id IN (SELECT x.id FROM (SELECT descendant_id AS id
                                             FROM comment_tree_paths
                                            WHERE ancestor_id = #{id}) AS x)
   AND ancestor_id IN (SELECT y.id FROM (SELECT ancestor_id AS id
                                           FROM comment_tree_paths
                                          WHERE descendant_id = #{id}
                                            AND ancestor_id != descendant_id) AS y)
SQL

    connection.execute <<SQL
INSERT INTO comment_tree_paths (ancestor_id, descendant_id)
  SELECT supertree.ancestor_id, subtree.descendant_id
    FROM comment_tree_paths AS supertree
      CROSS JOIN comment_tree_paths AS subtree
   WHERE supertree.descendant_id = #{parent.id}
     AND subtree.ancestor_id = #{id}
SQL
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>